### ISSUE TITLE
Login: Weiterleiten auf Home mit korrektem Scope im Token

### ISSUE THREAD

**Issue by fbufbi** [bkd-mba-fbi/evento-portal#106]
Problem:
- Einloggen mit Rolle, die den Scope "NG" hat. Navigieren im Evento Portal auf Seite "Administration > Anmeldedetails einlesen"
- Ausloggen
- Einloggen mit anderer Rolle, die diese Permission nicht hat > Weiterleitung auf Home funktioniert, aber es kommt eine Fehlermeldung zum Scope

Notification im GUI:
![image](https://github.com/bkd-mba-fbi/evento-portal/assets/49237948/5c0f6ce4-79ea-487b-9419-9c72482b0d05)

Fehlermeldung: `"Application scope NG does not allow access to GET http:\/\/eventoapp-test.apps.be.ch:17004\/ApiPublic\/Students\/1623\/LessonAbsences"`

Lösung: Beim Weiterleiten auf Home muss in jedem Fall der korrekte Scope im Token hinterlegt sein

Beispiel: GYM BIVO
- su@test.ch: Rolle mit Scope "NG" (su = Superuserin)
- l1@test.ch: Rolle ohne diesen Scope

**Comment by hupf** [comment]
@fbufbi
- Mit welchen zwei konkreten Users auf welcher Instanz können wir dieses Problem nachstellen?
- Was ist das eigentliche Problem? Handelt es sich um ein "kosmetisches Problem", weil unerwünschte Fehlermeldungen angezeigt werden? Oder funktioniert die Seite nach der Umleitung nicht korrekt (weil Scope falsch gesetzt oder so)?
- Wo wird die erwähnte Fehlermeldung angezeigt? In der Console? Dann gibt es auch eine Notification, welche nicht erscheinen sollte?

**Comment by fbufbi** [comment]
> @fbufbi
> 
> * Mit welchen zwei konkreten Users auf welcher Instanz können wir dieses Problem nachstellen?
> * Was ist das eigentliche Problem? Handelt es sich um ein "kosmetisches Problem", weil unerwünschte Fehlermeldungen angezeigt werden? Oder funktioniert die Seite nach der Umleitung nicht korrekt (weil Scope falsch gesetzt oder so)?
> * Wo wird die erwähnte Fehlermeldung angezeigt? In der Console? Dann gibt es auch eine Notification, welche nicht erscheinen sollte?

1. Siehe oben - neue DB: ID Mandant = GymBivo
2. Es wird der Userin eine Fehlermeldung (Notification) angezeigt, die Umleitung auf die Einstiegsseite funktioniert aber. 
3. Notification für die Userin und zusätzlich oben erwähnter Fehler in der Konsole. Ja, Notification für die Userin soll nicht erscheinen.

**Comment by fbufbi** [comment]
@hupf Der in der Beschreibung geschilderte Fall funktioniert. Der umgekehrte Weg führt aber zu vielen Unschönheiten:
- Login mit l1@test.ch > Tests und Bewertung > Klick auf Link "Tests erfassen" im Fach Englisch-S3, 27a
- Ausloggen
- Login mit su@test.ch > "leere" Anzeige im Bereich Tests (keine Weiterleitung auf Home):
![image](https://github.com/bkd-mba-fbi/evento-portal/assets/49237948/6c56a518-969b-4959-a373-cd02da69a8ba)
- Der Request `/Courses/9742?expand=ParticipatingStudents,EvaluationStatusRef,Tests,Gradings,FinalGrades,Classes` bringt 403 Forbidden (Antwort: "No access to domain object Course with id 9742")
- Konsole: Type Error: Cannot read properties of null (reading 'length')
- Klick auf Home > Fehlermeldungen, Konsole: Type Error: Cannot read properties of null (reading 'length')
![image](https://github.com/bkd-mba-fbi/evento-portal/assets/49237948/c449e05d-c68f-46fc-b4b2-21de23e8d084)

**Comment by hupf** [comment]
@fbufbi IMO haben die beschriebenen Fehler nichts mit dem Portal oder dem Login-Handling zu tun. Das Portal weiss nur, ob du grundsätzlich (gemäss Rolle) Zugriff auf das Tests Modul hast, nicht aber ob du Zugriff auf einen bestimmten Event oder Test hast.

Ist der su@test.ch richtig konfiguriert? Weil offenbar hat der auf keinen Event Zugriff (Liste ist leer). Und auch in der Präsenzkontrolle gibt es 403 Responses...

Was man allerdings sagen kann, ist dass wir in der WebApp die 403er noch nicht wirklich sauber handhaben. Deshalb kommt es in diesen Fällen zu Fehlern auf der Konsole. Ich schlage vor, dass wir dafür ein neues Ticket machen, wenn das realistische Szenarien sind, was meinst du?

**Comment by hupf** [comment]
@fbufbi Der erwähnte Fehler `Type Error: Cannot read properties of null (reading 'length')` (Chrome) resp. `TypeError: e.tests is null` (Firefox) passiert wegen fehlendem 403-Error Handling in der WebApp hier:

https://github.com/bkd-mba-fbi/webapp-schulverwaltung/blob/main/src/app/events/components/tests-list/tests-list.component.html#L14

**Comment by fbufbi** [comment]
Neues Ticket für Type Error, siehe #131 
Dieser Task wird geschlossen.
