### ISSUE TITLE
Stellvertretung aktiv HolderRoles übernehmen

### ISSUE THREAD

**Issue by schefbi** [bkd-mba-fbi/evento-portal#115]
Ist eine Stellvertretung aktiv sollen für die Navigation wie auch für die webapp-schulverwaltung die `holder_roles` aus dem Token genutzt werden.

Im `\evento-portal\src\settings.ts` können dann die` allowedRolesOrPermissions > AbsenceAdministratorRole` bei den keys `presenceControl, currentEvents, tests, openAbsences` entfernt werden.

Grund: Wenn sich ein Benutzer nur mit den Rollen `AbsenceAdministratorRole` und `SubsititionAdministratorRole` einloggt, sollte er die Navigation von `presenceControl`, `currentEvents`, `tests`, `openAbsences` nicht sehen, weil er wegen fehlender Rollen `LessonTeacherRole`, `TeacherRole` und `ClassTeacherRole` keinen Zugriff hat (Anzeige Fehlermeldungen oder kein Daten). Falls er aber eine Stellvertretung einer Lehrperson übernimmt, muss er zur Ausführung der Stv die Navigationseinträge sehen, da er diese Rollen nun in den `holder_roles` hat.

Beispiele: su (Superuserin) > sieht die oben erwähnten Nav-Einträge nicht (da keine Lehrperson / entsprechende Rollen); Stv. von B. Schmid übernehmen > sieht die Nav-Einträge (da nun Lehrperson)

**Comment by schefbi** [comment]
> @schefbi
> 
> * Für was sollen diese `holder_roles` aus dem Token «genutzt werden» während Stellvertretungen?
> * Wieso soll dann die Einschränkung `AbsenceAdministratorRole` bei den genannten Navigationseinträgen entfernt werden? Die aktuelle Einschränkung auf die Rolle greift ja auch wenn keine Stellvertretung aktiv ist...

UseCase: Wenn ein Benutzer nur mit der Rolle AbsenceAdministratorRole und SubsititionAdministratorRole einloggt. Sollte er die Navigation von presenceControl, currentEvents, tests, openAbsences nicht sehen, weil er keine Zugriffe darauf hat. Da er keine Rolle LessonTeacherRole, TeacherRole und ClassTeacherRole hat (Anzeige Fehlermeldungen oder kein Daten). Falls er aber eine Stellvertretung eines Lehrer/in übernimmt sollte er erst die Navigationseinträge sehen (holder_roles). 

Am besten wir besprechen das Heute noch.

**Comment by hupf** [comment]
@schefbi Dies haben wir heute noch vergessen zu besprechen beim Kickoff. Wir verstehen es immer noch nicht. Können wir nächste Woche einen Call machen?

**Comment by hupf** [comment]
@schefbi Also ich fasse mal zusammen was ich meine verstanden zu haben:

1. Wir entfernen bei den NavigationItems `presenceControl`, `currentEvents`, `tests` und `openAbsences` die Rolle `AbsenceAdministratorRole` (komplett, ohne Condition oder so)
2. Falls eine Stellvertretung aktiv ist (d.h. `substitution_id` in Token ist vorhanden), sollen wir statt

**Comment by hupf** [comment]
@schefbi Kannst du mir noch ein konkretes Beispiel für GymBivo sagen, wie ich dieses Feature testen kann?

**Comment by schefbi** [comment]
@hupf Du kannst auch den User su@test.ch nehmen. Der hat die AbsenceAdministratorRole. Danach kansst du die Sofort Stv. für Schmid Benjamin übernehmen.

**Comment by schefbi** [comment]
Test OK.
