### ISSUE TITLE
Kursauschreibung scrolling und iframe sizing

### ISSUE THREAD

**Issue by schefbi** [bkd-mba-fbi/evento-portal#117]
- Bei der Kursauschreibungsapp funktioniert das scrolling wie im [Wiki ](https://github.com/bkd-mba-fbi/kursausschreibung/wiki/Content-design)beschrieben nicht mehr. bsp. https://www.biz.bkd.be.ch/de/start/veranstaltungen/veranstaltungskalender.html#/veranstaltungsthemen
- Das iFrame wird bei der Kursauschreibungsapp nicht mehr kleiner wenn es einmal gross war.

<img width="494" alt="image" src="https://github.com/bkd-mba-fbi/evento-portal/assets/41326409/b0b437ba-3204-4222-bb08-7d3c9ead478c">

**Comment by hupf** [comment]
@schefbi
- Workaround für das iframe Resizing Problem mit der Kursausschreibung App umgesetzt.
- `window.scrollTo`/`window.scroll`, `window.scrollBy`, `window.scrollY`/`window.pageYOffset` und `Element.prototype.scrollIntoView` im `iframe.js` monkey-patched, damit diese das Scrolling im Portal statt im iframe durchführen. Bei `scrollIntoView` ist die Implementation nur rudimentär (d.h. Optionen wie `alignToTop`, `inline` und `block` werden nicht unterstützt). Was weiterhin nicht klappt sind `scroll` Events innerhalb des iframes. Da habe ich keine Schnelle Lösung gefunden.
- Schulverwaltung: Der Mechanismus mit dem Merken der Scrollposition (z.B. von Präsenzkontrolle Liste zum Detail und zurück) hatte noch einen Bug, den habe ich gefixt.
- Schulverwaltung: Infinite Scrolling (z.B. bei Absenzen bearbeiten) geht weiterhin nicht, es gibt aber den Fallback Button.

**Comment by schefbi** [comment]
Test OK.
