### ISSUE TITLE
Klick auf Report /events/{id}/tests zurück /events

### ISSUE THREAD

**Issue by schefbi** [bkd-mba-fbi/evento-portal#136]
Wenn auf den Report bei der /events/{id}/tests geklickt wird. Wird der Report in einem neuen Tab geöffnet das Tab des events wechselt auf /events zurück und bleibt nicht auf /events/{id}/tests.

Testen 
GymBivo > l1@test.ch
#/events/9742/tests

**Comment by hupf** [comment]
Habe die ursprüngliche Änderung wieder rückgängig gemacht und das Problem auf Ebene der `erz-backlink` Komponente gelöst. Nun sollte nur noch ein Klick auf den Link selber die Navigation auslösen.

**Comment by schefbi** [comment]
@hupf  

- [ ] Beim klick auf den zurück Button wird auf folgende URL gewechselt:  https://evtapp.netlify.app/apps/webapp-schulverwaltung/index.html#/events
- [ ] Beim Klick auf einen Test in der Excel-Eingabe wird das Input Form nicht mehr geöffnet.

**Comment by hupf** [comment]
Sorry 🤦‍
→ https://github.com/bkd-mba-fbi/webapp-schulverwaltung/pull/656

**Comment by schefbi** [comment]
@hupf Beide Punkte funktionieren nun einwandfrei. Test Ok
