### ISSUE TITLE
Console Fehler /settings.example.js status 404

### ISSUE THREAD

**Issue by schefbi** [bkd-mba-fbi/evento-portal#138]
In der console haben wir den Fehler das /settings.example.js nicht geladen werden kann. Das sollte doch gar nicht abgefragt werden?
![image](https://github.com/bkd-mba-fbi/evento-portal/assets/41326409/4b106c16-c957-44a6-b5be-b19079a87a9e)

```
workbox-fa446783.js:1  Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://evtapp.netlify.app/settings.example.js","status":404}]
    at E.O (https://evtapp.netlify.app/workbox-fa446783.js:1:10472)
    at async E._ (https://evtapp.netlify.app/workbox-fa446783.js:1:10024)
    at async E.U (https://evtapp.netlify.app/workbox-fa446783.js:1:9148)
```

**Comment by hupf** [comment]
@schefbi
- `settings.js` und `settings.example.js` werden nun nicht mehr vom Service Worker pre-fetched
- Neu habe ich auch noch implementiert, dass wenn man auf der Offline-Page ist und wieder online geht, die App automatisch neu geladen wird. Ansonsten hat man irgendwie gar nicht wirklich die PWA zu refreshen, ausser die abzuschiessen.

**Comment by schefbi** [comment]
Test OK.
