### ISSUE TITLE
add Cache-Control: no-cache to all index.html pages

### ISSUE THREAD

**Issue by schefbi** [bkd-mba-fbi/evento-portal#149]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control?retiredLocale=de

Cache-Control: no-cache

**Comment by hupf** [comment]
@schefbi Können wir das effektive Problem noch einmal zusammen besprechen? Ich würde eine Lösung vorziehen in der nicht einfach das Caching ausgeschaltet wird...

**Comment by schefbi** [comment]
@hupf Spannend wenn ich die app Lokal starte wird auch die index.html des iframe mit 304 gemeldet.

<img width="583" alt="image" src="https://github.com/bkd-mba-fbi/evento-portal/assets/41326409/05921166-882e-4487-a01f-8f1ccca2db9b">

Hier wird gegenüber des Test und Prod Servers `Cache-Control: no-cache` mitgegeben. Auf dem Netlify Server wird `Cache-Control: public,max-age=0,must-revalidate`

**Comment by hupf** [comment]
@schefbi
- Beim produktiven Build ist natürlich nun der Service Worker im Spiel, welcher z.B: das /index.html cached. Das ist der Grund weshalb es dort ein unterschiedliches Verhalten gibt zum webapp index.html.
- Weisst du ob das Problem auf dem aktuellen Produktionsstand (noch ohne Service Worker) aufgetreten ist? Oder schon mit Service Worker? Weil bei letzterem könnte es auch ein Problem mit dem Aktualisieren/Caching des Service Workers sein...
- Ich habe jetzt auf jeden Fall den Nginx mal so konfiguriert, dass immer der `no-cache` Header gesetzt wird.

**Comment by schefbi** [comment]
@hupf Auf der Produktion hatte die Schule das gemerkt. Bei dieser Version hatten wir noch keine Serviceworker integriert. Ich werde diese Version nun einmal auf Test deployen dann können wir sehen ob es sich korrekt verhält.

**Comment by schefbi** [comment]
@hupf Es kommt auf evt-test.apps.be.ch immer noch ein 200er es müsste doch ein 304 kommen?
![image](https://github.com/bkd-mba-fbi/evento-portal/assets/41326409/5f32965b-e964-4c10-a688-2b8c41059dbb)

**Comment by schefbi** [comment]
Gemäss Meeting auf no-cache umstellen.

Note that no-cache does not mean "don't cache". no-cache allows caches to store a response but requires them to revalidate it before reuse. If the sense of "don't cache" that you want is actually "don't store", then no-store is the directive to use.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control?retiredLocale=de
