### ISSUE TITLE
Tests: Schaltfläche Excel-Import einbinden

### ISSUE THREAD

**Issue by fbufbi** [bkd-mba-fbi/evento-portal#155]
Aufgrund von Änderungen am Layout ist die Schaltfläche "Excel-Import" vom X.js nicht mehr vorhanden.

**Comment by schefbi** [comment]
Korrigiert https://github.com/bkd-mba-fbi/evento-portal/pull/156

**Comment by fbufbi** [comment]
Test OK, vielen Dank
