### ISSUE TITLE
Nach Ausloggen beim Login auf die Startseite (Dashboard)

### ISSUE THREAD

**Issue by fbufbi** [bkd-mba-fbi/evento-portal#159]
Wenn sich jemand selber ausgeloggt hat (sprich: nicht wegen Ablauf des Tokens o.ä. aus Evento Web geworfen wurde), soll diese Person beim nächsten Einloggen auf die Startseite (Dashboard) kommen, nicht auf die zuletzt vor dem Logout besuchte Seite.

Use case: Lehrpersonen befinden sich am aktuellen Tag zuletzt in der Präsenzkontrolle. Sie loggen sich aus und am nächsten Tag wieder ein. Sie werden dabei zurzeit direkt auf die Präsenzkontrolle von gestern weitergeleitet, was für heute nicht mehr stimmt und irritiert.

Beispiel: GymBivo, l1

**Comment by fbufbi** [comment]
@hupf Da wir Token Rotation zurückstellen, bliebt evtl. noch etwas Budget übrig. Wäre dieser Task noch etwas für die nächsten Tage, falls ihr Zeit habt? Bei Fragen stehen wir euch zur Verfügung.

**Comment by hupf** [comment]
@fbufbi Ich denke wir könnten das so lösen, dass wir beim Logout das Dashboard als Redirect URL mitgeben. Allerdings führt dies möglicherweise zu unerwartetem Verhalten. Wenn ich z.B. mehrere Tabs offen habe auf unterschiedlichen Seiten, wäre ich am nächsten Tag bei allen Tabs wieder auf dem Dashboard, statt dort wo ich eigentlich war. Ist das wirklich gewünscht?

**Comment by fbufbi** [comment]
> @fbufbi Ich denke wir könnten das so lösen, dass wir beim Logout das Dashboard als Redirect URL mitgeben. Allerdings führt dies möglicherweise zu unerwartetem Verhalten. Wenn ich z.B. mehrere Tabs offen habe auf unterschiedlichen Seiten, wäre ich am nächsten Tag bei allen Tabs wieder auf dem Dashboard, statt dort wo ich eigentlich war. Ist das wirklich gewünscht?

@hupf Dein Beispiel klingt für mich nach einem unfreiwilligen / unbewusstem Logout aufgrund des Sessionendes. Ein solches Logout dürfte nicht betroffen sein, denn dann ist das Weiterarbeiten am Ort, wo man zuletzt war, (wohl) erwünscht. Mein Use case betrifft nur das "bewusste" Logout - ich klicke aktive auf Logout. Wenn ich mehrere Tabs offen habe und ich mich bei einem bewusst auslogge, ja dann käme ich beim neuen Login auf die Startseite/Dashboard.

Verstehst du den Unterschied und ist dieser überhaupt zu machen?

**Comment by hupf** [comment]
@fbufbi Ja, da hast du natürlich recht – sorry, ich hatte ein Fehlüberlegung gemacht. Ich denke wir sollten das nur beim aktiven Logout machen können. Ich schaue es mir nächste Woche an.

**Comment by fbufbi** [comment]
Test OK
