### ISSUE TITLE
Sprachumstellung DE/FR für einsprachige Schulen ausblenden (Konfiguration)

### ISSUE THREAD

**Issue by fbufbi** [bkd-mba-fbi/evento-portal#166]
IST: Der Sprachswitcher ist immer eingeblendet
![image](https://github.com/bkd-mba-fbi/evento-portal/assets/49237948/17a7cba6-1b17-49d1-85be-202701344b0c)

SOLL:
- Bei einsprachigen Schulen (DE oder FR) soll der nicht zutreffende Eintrag deaktiviert (ausgegraut) sein. Oder falls möglich: Sprachswitcher ganz ausgeblenden.
- Bei einsprachiger Schule muss nach dem Login immer auf die jeweilige Sprache dieser Schule gewechselt werden, unabhängig davon was in URL, Token etc. steht (Spracherkennungsmechanismus entsprechend anpassen).

Use case einsprachige GYM/FMS DE: Die Werte der formativen Beurteilung werden im Web nur auf Deutsch angezeigt. Bei Umstellung der Websprache auf FR erscheinen leere Dropdowns. Es ist aber sowieso nicht korrekt, diese Werte auf Französisch einzugeben, weil der Zwischenbericht einsprachig Deutsch sein muss.

- [ ] Umsetzung soll auch im OAuth form gemacht werden, damit Benutzer/innen nicht mit einer nicht konformen Mandant GUI Sprache ein Login machen.

Technische Umsetzung:
Im untenstehenden Request wird eine neue Eigenschaft `guiLanguage` (array) erstellt, die die Sprache des jeweiligen Mandanten beinhaltet.

`Get /Configurations/SchoolAppNavigation/`

Body:
```
{
  "instanceName": "BS-Test"
  "guiLanguage": ["de-CH","fr-CH"]
}
```

**Comment by hupf** [comment]
@fbufbi Aufgrund von welchem Kriterium können wir erkennen ob eine Schule ein- oder zweisprachig ist. Können wir das vom Backend laden (wenn ja, wie konkret) oder werden im Settings Files die IDs der entsprechenden Schulen statisch gepflegt?

**Comment by fbufbi** [comment]
> @fbufbi Aufgrund von welchem Kriterium können wir erkennen ob eine Schule ein- oder zweisprachig ist. Können wir das vom Backend laden (wenn ja, wie konkret) oder werden im Settings Files die IDs der entsprechenden Schulen statisch gepflegt?
> 
> Aus unserer Sicht die Anzeige nur einer Sprache keinen Sinn. Wir würden den Sprachswitcher komplett ausblenden.

@hupf Da hast du natürlich recht - wir blenden den Sprachswitcher komplett aus. Ich passe das in der Beschreibung an.
@schefbi Aufgrund von welchem Kriterium können wir erkennen, ob eine Schule ein- oder zweisprachig ist?

**Comment by schefbi** [comment]
@hupf Ich habe die technische Umsetzung ergänzt. Im OAuth Form werden wir das auch so implementieren, damit nicht mit nicht konformen GUI Sprachen eingeloggt wird.

**Comment by caebr** [comment]
@schefbi Wenn ich einen Request auf den obigen Endpunkt absetzte, bekomme ich nach wie vor nur den "instanceName" in der Response.

Muss beim Request noch etwas spezielles mitgegeben werden oder ist das Feature (auf der Test-Umgebung) noch nicht implementiert?

**Comment by schefbi** [comment]
@caebr Sorry ich habe das noch nicht gemacht, weil ich vermeiden wollt das es nicht ein zu einem decode error kommt. Auf Gym Bivo habe ich es erfasst. Ich werde das nun auf allen Mandanten machen.

**Comment by caebr** [comment]
@schefbi Super, danke!

**Comment by schefbi** [comment]
Auf dem Mandant _Schule für Holzbildhauerei_ habe ich l1@test.ch eingerichtet diese Schule hat nur de-CH

**Comment by hupf** [comment]
> @caebr Sorry ich habe das noch nicht gemacht, weil ich vermeiden wollt das es nicht zu einem decode error kommt. Auf Gym Bivo habe ich es erfasst. Ich werde das nun auf allen Mandanten machen.

@schefbi Zusätzliche Attribute werden übrigens einfach ignoriert, ein Decode Error gibt es nur wenn ein definiertes Attribut nicht vorhanden ist oder einen anderen Type vorweist.

**Comment by fbufbi** [comment]
@caebr In der Redirect-URL ist die `culture_info=undefined`. Damit kommt auf der Login-Seite ein interner Fehler.

**Comment by schefbi** [comment]
Test OK. 
@fbufbi Ich schlage vor das wir die Logik nicht im OAuthLoginForm integrieren, damit wir nicht zusätzlich Komplexität ins Form integrieren müssen und auch warten müssen. Das Portal wurde so umgesetzt falls man mit bsp. fr-CH einloggt aber der Mandant nur de-CH anbietet das Token mit de-CH erstellt wird.
