### ISSUE TITLE
Neue Seiten Kontakt, Rechtliche Hinweise und Impressum / Verlinkung im Footer

### ISSUE THREAD

**Issue by fbufbi** [bkd-mba-fbi/evento-portal#167]
Abklärung mit STA-KomBE: Die Fachapplikation soll die im Footer verlinkten Seiten selber beinhalten (die BKD möchte keine versteckten Seiten erstellen).
- Kontakt
- Rechtliche Hinweise
- Impressum

- [x] Vorschlag für KomBE erarbeiten
- [x] Übersetzung auf FR - bis 22.03.2024
- [x] Einbindung in Footer

Gemäss [CI/CD](https://www.cd.sites.be.ch/d/mLaezX2xseW6/anwendungen#/web-mobile/web/footer)

![image](https://github.com/bkd-mba-fbi/evento-portal/assets/49237948/747137e3-da66-4ae2-ae9d-d626af8b0d27)

**Comment by hupf** [comment]
@fbufbi Sind die Inhalte dieser Seite statisch (braucht einen Change + ein neues Deployment für eine Anpassung), oder komme sie vom Backend (d.h. aus der Datenbank)?

**Comment by schefbi** [comment]
@hupf und @fbufbi: Ja statisch. wir halten es im code und es ist für alle Mandanten identisch.

**Comment by hupf** [comment]
@fbufbi Es betrifft nur die Verlinkung von Kontakt und Impressum. Bei den anderen Links habe ich einfach den Link Text (z.B. «E-Mail») übersetzt, die E-Mailadresse/URL ist nicht Teil der Übersetzung.

Betreffend Impressum, wie wäre es, wenn wir hier den Instanznamen anzeigen würden (wie im Header) und den Link einfach weglassen (weil im Kontakt steht ja dann sowieso nicht mehr konkretes):

![Screen Shot 2024-04-23 at 13 17 36](https://github.com/bkd-mba-fbi/evento-portal/assets/66047/ba5262de-0572-4fc9-8190-90b115c87e49)

Bei den beiden Verweisen auf das Impressum unter «Rechtliche Hinweise» ist die Frage:
- Können wir die Verlinkung des Wortes «Impressum» einfach weglassen? Die Users können dann einfach im Footer das Impressum öffnen.
- Oder wenn nicht, können wir den Text so umformulieren, dass wir den Link-Text als eigener Teil übersetzen können?

**Comment by fbufbi** [comment]
@hupf Bitte sowohl Kontakt und Impressum als Text stehen lassen und einfach nicht verlinken. Der Instanzname ist eine gute Idee, ist aber leider nicht immer ganz korrekt, daher lieber nicht.

**Comment by fbufbi** [comment]
@hupf Zwei Korrekturen bitte:

1. Contact: Falsch übersetzter Text in der Vorlage FR, den ich erst jetzt sehe: `L'école indique le service concerné.` (ohne "aux élèves", da die Schule dies allen vorher aufgeführten Personengruppen, also auch den Lehrpersonen & Mitarbeitenden kommuniziert)
![image](https://github.com/bkd-mba-fbi/evento-portal/assets/49237948/49c72076-b617-40ea-a50d-3b6ef904fcaa)

2. Rechtliche Hinweise DE/FR - Datenschutzerklärung/Politique de confidentualité: Link mba/omp in neuem Tab öffnen

**Comment by hupf** [comment]
@fbufbi Ich habe diese beiden Sachen noch angepasst, obwohl ich da nicht so grosser Fan von `target="_blank"` bin und es lieber den Users überlasse ob sie ein Link in einem neuen Tab öffnen wollen oder nicht.

**Comment by fbufbi** [comment]
Test OK

**Comment by fbufbi** [comment]
@schefbi Was machen wir hier? Deployen wir das Loginform ohne funktionierende Links im Footer? Entfernen wir sie?

**Comment by schefbi** [comment]
@fbufbi Ist deployed. Ich möchte das nicht rückgängig machen.
