### ISSUE TITLE
Login-Seite anpassen: Footer, Abstände

### ISSUE THREAD

**Issue by fbufbi** [bkd-mba-fbi/evento-portal#176]
Login-Seite anpassen:
- Zusätzlich Kontakt im Footer
- Verlinkung der Seiten Kontakt, Rechtliche Hinweise und Impressum
- Abstände anpassen: "Passwort vergessen" sollte näher ans PW-Feld heran, da es einen direkten Zusammenhang hat. ("Schule wechseln" hat hingegen keinen Zusammenhang zur E-Mail-Adresse)

![image](https://github.com/bkd-mba-fbi/evento-portal/assets/49237948/9b841fa7-de32-4312-a592-ff2bfd3d50da)
Header & Footer beim SOLL stammen aus dem eingeloggten Zustand.

**Comment by schefbi** [comment]
@fbufbi Auf dev habe ich die Seiten auf dem OAuth Server auf das Portal verlinkt, weil es auf dem gleich host läuft funktioniert das aber nicht. 

Welche abstände sollen noch angepasst werden?

**Comment by fbufbi** [comment]
@schefbi Problem: Auf der Login-Seite funktionieren die Links im Footer (Kontakt, Rechtliche Hinweis, Impressum) nicht. Erst nach dem Login klappt das. Das ist natürlich falsch, denn gerade bei nicht funktionierendem Login brauche ich den Kontakt... Leider hat niemand technisch daran gedacht. Wie können wir das im nächsten Projekt anders aufsetzen?
