### ISSUE TITLE
Evento akzeptiert Authorization Header

### ISSUE THREAD

**Issue by schefbi** [bkd-mba-fbi/evento-portal#178]
Evento akzeptiert neu den Authorization Header bei REST-API Anfragen.

`Authorization: Bearer {token}`

Mögliche Anpassung: Alle FBI-Module werden umgestellt, sodass sie das Token neu im Authorization Header übergeben anstelle der "Clx-Authorization".

**Comment by hupf** [comment]
Sowohl in der WebApp wie auch im Portal angepasst.
