### ISSUE TITLE
PWA (1PT)

### ISSUE THREAD

**Issue by caebr** [bkd-mba-fbi/evento-portal#61]
- [x] Web Manifest mit Icons etc. (Icon wird noch geliefert)
- [x] Installierbar (dummy Service Worker erstellen)

Muss nicht offline verfügbar sein

Abklärung mit STA-KomBE: Für die PWA wird das Wappen ohne Schriftzug verwendet (wie im Favicon), da der Schriftzug zu klein würde. Als Hintergrundfarbe wird eine [Sekundär- oder Tertiärfarbe](https://www.cd.sites.be.ch/d/mLaezX2xseW6/grundelemente#/farbwelt/farben/sekundaerfarben) gewählt (nur übergeordnete kantonale Applikationen sollen die Primärfarben für die PWA verwenden).

Name: Evento
Kurzname: Evento
Beschreibung: Schulverwaltungsapplikation des Kantons Bern
Hintergrundfarbe: #3C505A (Aare)
Theme color: #3C505A (Aare)
Icon: Kanton Bern (negativ in Weiss)

~Favicon: Kantonswappen wie bei BKD-Website~ → schon umgesetzt

**Comment by caebr** [comment]
@fbufbi 
- Könntest du noch das Icon liefern?
- Das Web Manifest verlangt nach einigen Infos (Name der App, Beschrieb, Farben etc.). Wir würden da einfach einen Vorschlag machen und nach Bedarf anpassen.

**Comment by fbufbi** [comment]
@caebr Manifest:
- Name: Evento
- Kurzname: EVT
- Beschreibung: Schulverwaltungsapplikation des Kantons Bern
- Hintergrundfarbe: #EA161F (rot)
- Icon: Kanton Bern - könnt ihr das bereits eingesetzte Favicon verwenden?

**Comment by schefbi** [comment]
@caebr  Lighthouse meint alles grün: 
![image](https://github.com/bkd-mba-fbi/evento-portal/assets/41326409/17a8e809-f7a8-4581-8dfa-801a3492848f)

**Comment by caebr** [comment]
@schefbi  Wir haben die PWA auf unseren Smartphones ausprobiert (mit Chrome und Firefox). Installation und Offline-Modus haben soweit funktioniert.

Was uns aber noch aufgefallen, dass das Icon noch nicht ganz ideal ist:

![pwa-icon](https://github.com/bkd-mba-fbi/evento-portal/assets/18602910/bcabf2cd-3e24-485b-936c-df5727f982ad)

Das können wir noch anschauen.

**Comment by schefbi** [comment]
@caebr Ich habe einmal die Kom Abteilung anschrieben.

**Comment by caebr** [comment]
@schefbi Wir haben Tool verwendet, welches uns die Bilder _theoretisch_ in den richtigen Formaten/Grössen generiert hat. Inbesondere ist ein "maskable" Icon nötig, damit das obige Problem eben genau nicht auftritt - aber etwas ist wohl noch nicht ganz richtig.

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Define_app_icons#support_masking

D.h. wir können ein entsprechendes Icon auch selber generieren.

Noch eine andere Frage: Ist EVT als Short-Name ok? Oder wäre Evento hier besser?

**Comment by schefbi** [comment]
@caebr Icons werden in der KW 1 oder 2 2024 von der kom.be.ch an ungesandt.

**Comment by fbufbi** [comment]
@schefbi Abklärung mit STA-KomBE in der Beschreibung ergänzt.
