### ISSUE TITLE
Token abgelaufen auf Login Seite weiterleiten

### ISSUE THREAD

**Issue by schefbi** [bkd-mba-fbi/evento-portal#63]
Wenn das Token abgelaufen ist, muss auf die Login Seite weitergeleitet werden, damit verhindert wird, dass den Benutzern die Meldung "nicht angemeldet" oder "kein Zugriff" angezeigt wird.

Umsetzung:
- Bei Ablauf des Access Tokens soll auf den Token Refresh weitergeleitet werden (Timer)
- Bei Ablauf des Refresh Tokens soll auf die Login Page weitergeleitet werden (Timer) → überprüfen ob dies schon gemacht wird

useCase:
Ich habe mich auf dem Portal mit meinem privaten Laptop eingeloggt. Danach habe ich ich 24h gewartet (standby modus) und im Portal nochmals auf einen Eintrag im webappschulverwaltung geklickt. Ich habe dort die Meldung "Nicht angemeldet oder kein Zugriff" erhalten. Das Problem ist das die apps sich nicht um die Tokens kümmern müssen.

**Comment by schefbi** [comment]
> Was aber passieren kann: Wenn ich eine Seite öffne und länger dort drauf bleibe als das Access Token gültig ist (egal ob mit aktivem Klicken oder nicht), dann kommt es zur Situation wo die App (z.B. Schulverwaltung) bei den Requests plötzlich 401 kriegt und eine Fehlermeldung anzeigt. In diesem Fall müsste der User aktuell sowieso reloaden. Was wir tun könnten ist ein Timer setzten, wenn das aktuelle Access Token abläuft und dann abrupt zum Token Refresh weiterleiten.

Ich denke das ist eine gute Lösung.

**Comment by schefbi** [comment]
@hupf  Bei den Test ist mir aufgefallen das ich nun gar nicht mehr aus der Applikation heraus fliege... Beim Refresh wird auch das Token refreshed mit neuem Datum was dazu führt das man nun immer eingeloggt bleibt.

Können wir morgen das Thema im daily diskutieren?

**Comment by hupf** [comment]
@schefbi Es gab ein Redirect Loop, wenn das Access Token ablief oder wenn die Seite neu geladen wurde und das Access Token bereits expired war. Mit dem neusten Fix wird der Timer nur gesetzt, wenn das Token nicht bereits abgelaufen ist – bei Tokens die bereits abgelaufen sind greift die normale Logik, wenn man auf die Seite kommt.

**Comment by schefbi** [comment]
@hupf Wir haben den neuen Release von SLH erhalten mit dem Token Refresh Rotation werde das noch mit dieser Version testen.
