### ISSUE TITLE
Action Retro Browserstack-Setup für Portal (ca)

### ISSUE THREAD

**Issue by schefbi** [bkd-mba-fbi/evento-portal#69]
Muss noch genau definiert werden was das heisst.

Consumer erfassen im OAuth für Browserstack https://bs-local.com:3000

**Comment by hupf** [comment]
- Grundsätzlich kann bei BrowserStack der Traffic lokal durchgerouted werden, dann funktioniert es → noch einmal verifizieren
- Bei Mac/iOS wird statt localhost bs-local.com verwendet
  - bs-local.com zusätzlich zu localhost bei BKD-SSO als erlaubter Redirect-Host hinterlegen
  - Die App sollte lokal für bs-local.com gestartet werden können (damit der Redirect dann auch funktioniert) + im /etc/hosts File bs-local.com auf 127.0.0.1 zeigen lassen

**Comment by hupf** [comment]
Wir haben nun ein Setup, der mit BrowserStack funktioniert. Dokumentation ist im Repo:
https://github.com/bkd-mba-fbi/evento-portal/blob/main/doc/browser-support.md
